### PR TITLE
Support k8s 1.7.x

### PR DESCRIPTION
**Pull request by samba**
Currently still work in progress. 

As Helm is still pending their release to support 1.7, this current revision has a few hacks that *will be revisited* before merge is appropriate. 

Relates to samsung-cnct/k2#607.

### CODE REVIEW

**Comment by coffeepac** [comment]
we do not wait for helm support before we support a kubernetes release.  we have put forth a decent amount of effort to handle the case where helm does not support the latest version of kubernetes.  

the correct thing to do for this PR is to not include anything related to HELM + kubernetes 1.7 support and leave the helm latest refs pointing to helm + kubernetes 1.6.  the weekly on-call check will see when the next version of helm is released and we can update k2-tools then

**Comment by samba** [comment]
Acknowledged, @coffeepac. 

Something's awry in the previous linking structure then. When loading k8s 1.7, I was left with a container that had Helm for previous versions but not 1.7, and could not complete a deploy with the other tooling (i.e. Ansible). It would fail due to Helm apparently missing.  The hacks here were simply to work around that, focused on getting a functional 1.7 cluster.

If I read you correctly, that failure is *not* expected. Perhaps due to revisit?

**Comment by coffeepac** [comment]
no, those failures are expected but not thought out in the ways of CI.  you may need to alter the config file munging to include adding a flag for handling helm not being present correctly.  the check to satisfy is here:  https://github.com/samsung-cnct/k2/blob/master/ansible/roles/kraken.config/tasks/helm-versioning.yaml#L8

you could probably modify the current sed command that sets the name of the cluster to include a newline, an appropriate amount of spaces (YAML!) and then `helmOverride: true`

thats a bit ugly but our current helm dependency is a bit ugly

**Comment by samba** [comment]
@coffeepac Cleaned up the `Makefile` linking & such, this should be ready for review/release.

**Pull request merged**
