### PR TITLE
convert to new names as appropriate

### PR DESCRIPTION
**Pull request by coffeepac**

### CODE REVIEW

**Comment by alika** [comment]
I saw a reference to `k2-tools` in `build/alpine-builds/runme.sh`.  Should this be renamed as well?

**Comment by coffeepac** [comment]
we aren't migrating docker repository references right now.  that'll be a follow-on PR and will probably require us to publish multiple copies of each image as we swap over.

**Comment by coffeepac** [comment]
`kraken-lib` not `Kraken-lib`, etc

**Comment by yenicapotediaz** [comment]
Why is it kraken-lib and not Kraken-lib?

**Pull request merged**
