### PR TITLE
Add etcdctl

### PR DESCRIPTION
**Pull request by davidewatson**

### CODE REVIEW

**Comment by alejandroEsc** [comment]
is 3.2.1 the same version of etcd on k2?

**Comment by alejandroEsc** [comment]
Just a question about version, otherwise LGTM

**Comment by davidewatson** [comment]
It depends on the k2 configuration file. By default, v3.1.0 is specified.

I am not opposed to installing the latest patch version for the default minor version, it's probably a good idea. The [documented](https://github.com/coreos/etcd/tree/master/etcdctl) support policy could bite us if/when someone starts depending on the output of etcdctl.

Note that I am purposely not installing etcdctl such that it can be (easily) versioned at this time. I want to avoid such a situation if at all humanly possible.

**Comment by alejandroEsc** [comment]
May be worth on being consistent with our default version and allow k2 dev to decide if their cluster and tooling should be consistent.

**Comment by venezia** [comment]
I think its a little bit of a boondoggle though.  Is there anything stopping us from using etcd in a container so that the version always matches whatever the cluster was configured to use?

**Comment by davidewatson** [comment]
I think it will be less error prone if we avoid DnD and pulling images at runtime. As for the latter benefit, if we pull the image at build time then we have the same version mismatch problem we were trying to avoid.

**Comment by mikeln** [comment]
Pulling executables at runtime...hmm.   (I get the version concern).
I suppose the longer startup time isn't an issue.   But it just feels wrong. 
(I have no solution though).

**Comment by davidewatson** [comment]
@mikeln Agreed that pulling at runtime is disagreeable. Since all I really want is _a_ version of etcdctl to support etcd liveliness checks for now, is there any disagreement to tabling the version concerns for now?

**Pull request merged**
