### PR TITLE
Make gcloud install the same way google does it

### PR DESCRIPTION
**Pull request by joejulian**
This copies the install process from GoogleCloudPlatform/cloud-sdk-docker
which happens to create a still smaller image.

This may also fix samsung-cnct/k2#616

### CODE REVIEW

**Comment by davidewatson** [comment]
LGTM.

**Comment by coffeepac** [comment]
This PR was hijacked and expanded to include a larger amount of CI.  @davidewatson do you mind doing another review?

**Comment by davidewatson** [comment]
Sure.

**Comment by davidewatson** [comment]
Per our conversation, it may be useful to split out these k2 integration tests out of k2-tools, but that can wait until we decide on a direction going forward.

**Pull request merged**
