### PR TITLE
add release path to Jenkinsfile

### PR DESCRIPTION
**Pull request by coffeepac**
k2-tools work in support of samsung-cnct/k2#376

### CODE REVIEW

**Comment by guineveresaenger** [comment]
Newbie question because this is relevant to k2-cli work: 

so, the test stage only runs on non-releases. Why? Is there SOP for only making a release PR on already checked and tested PRs? This would make sense to me, but exactly how does this happen? Are there safeguards, or is it just procedure?

Also curious how/where version gets added to the env.

**Comment by coffeepac** [comment]
Answers:
- this PR assumes that we will only tag code after it has passed CI.  I am leaving that concern out because a. it lets me test things easier and b. I'm not sure we need to run CI again against code that has already been vetted.  I am not settled on this though, so I'm welcoming discussion.
- env.RELEASE_VERSION gets injected into the environment by Jenkins.  The value is selected by the operator from a list of tags in the repo.

**Comment by guineveresaenger** [comment]
@coffeepac thank you for the answers! wow, my notifications have really been delayed lately, or something. Waiting for CI to pass...

**Comment by coffeepac** [comment]
need to not have this running for real for a bit.  will reopen hopefully later today.

**Pull request merged**
