### PR TITLE
freeze python packages, add some text to the README

### LINKED ISSUE #17: Fix versions installed in k2-tools container
k2-tools currently does this:

Python / ansible addon work

    # update pip
RUN pip install --upgrade pip
# Adding netaddr
RUN pip install netaddr

Instead it should use a requirements.txt file to ensure Python versions do not drift when the container image is rebuilt.

### PR DESCRIPTION
**Pull request by coffeepac**
the readme needs more work but this is fine for now.

requirements.txt was generated by running 'pip freeze' in the current
latest image for k2-tools.  removed the manual install of netaddr
and boto as those are now in the requirements file.

this is the build link from quay:  https://quay.io/repository/samsung_cnct/k2-tools/build/86be1ba6-f510-4212-a8a8-e142b057b24b
this is the github link to the exact ref:  https://github.com/samsung-cnct/k2-tools/commit/b2f541487e0533ce761088b4d2e0ee6f8192126f

this resolves #17

### CODE REVIEW

**Comment by joejulian** [comment]
LGTM

**Comment by leahnp** [comment]
^ ideas on how I can test this?

**Comment by coffeepac** [comment]
@leahnp pull down the current k2-tools docker image, run 'pip freeze' make sure the output from your command matches what is in requirements.txt

**Comment by spiffxp** [comment]
lgtm 

Imma merge it, @coffeepac said I could

**Pull request merged**
