### PR TITLE
updated ansible version

### PR DESCRIPTION
**Pull request by DStorck**
this is to fix the divide by zero issue on destroying ELBS in https://github.com/samsung-cnct/k2-tools/issues/42

### CODE REVIEW

**Comment by NathanZook** [comment]
Did you remember to update README.md?

**Comment by davidewatson** [comment]
Is there any reason not to change the README.md to point to the requirements.txt for the correct version? Keeping documentation consistent in two places is error prone.

**Comment by coffeepac** [comment]
this version is only specified in k2's readme.  k2-tools's readme is barren at best.  we could say 'ansible 2.x (see k2-tools for exact version)' and then do the same with the terraform providers.  would that work for you two @NathanZook  and @davidewatson ?  If so, I'll file a ticket

**Comment by davidewatson** [comment]
Works for me. I've submitted https://github.com/samsung-cnct/k2/pull/423

**Pull request merged**
